---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tutorial.study.dev
  resources:
  - secsynches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorial.study.dev
  resources:
  - secsynches/finalizers
  verbs:
  - update
- apiGroups:
  - tutorial.study.dev
  resources:
  - secsynches/status
  verbs:
  - get
  - patch
  - update
